// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vbqcchrggphfdupxitgq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZicWNjaHJnZ3BoZmR1cHhpdGdxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzNTEzNDYsImV4cCI6MjA3NDkyNzM0Nn0.w3n3mJJj8PTlrIG0GN19ECUbIXV0o9UG6T1MLfSW79c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});